bedrock/legal/urls.py
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

from django.urls import path

from bedrock.legal import views
from bedrock.legal_docs.views import LegalDocView
from bedrock.mozorg.util import page

urlpatterns = (
    page("", "legal/index.html", ftl_files=["mozorg/about/legal"]),
    page("eula/", "legal/eula.html"),
    page("eula/firefox-2/", "legal/eula/firefox-2-eula.html"),
    page("eula/firefox-3/", "legal/eula/firefox-3-eula.html"),
    page("eula/thunderbird-1.5/", "legal/eula/thunderbird-1.5-eula.html"),
    page("eula/thunderbird-2/", "legal/eula/thunderbird-2-eula.html"),
    # issue #11383 The template is hard-coded English
    page("firefox/", "legal/firefox.html"),
    # issue #12332 The template is hard-coded English
    page("terms/staycation/", "legal/terms/staycation.html", ftl_files=["mozorg/about/legal", "privacy/index"]),
    # The "impressum" page is intended for Germany. Redirect to German (de) if
    # requested in any other locale. (Bug 1248393)
    page("impressum/", "legal/impressum.html", active_locales=["de"], ftl_files=["mozorg/about/legal"]),
    path("terms/mozilla/", LegalDocView.as_view(template_name="legal/terms/mozilla.html", legal_doc_name="Websites_ToU"), name="legal.terms.mozilla"),
    path(
        "terms/firefox/",
        LegalDocView.as_view(template_name="legal/terms/firefox.html", legal_doc_name="firefox_about_rights"),
        name="legal.terms.firefox",
    ),
    path(
        "terms/firefox-reality/",
        LegalDocView.as_view(template_name="legal/terms/firefox-reality.html", legal_doc_name="firefox_reality_about_rights"),
        name="legal.terms.firefox-reality",
    ),
    path(
        "terms/firefox-private-network/",
        LegalDocView.as_view(template_name="legal/terms/firefox-private-network.html", legal_doc_name="Firefox_Private_Network_ToS"),
        name="legal.terms.firefox-private-network",
    ),
    path(
        "terms/thunderbird/",
        LegalDocView.as_view(template_name="legal/terms/thunderbird.html", legal_doc_name="thunderbird_about_rights"),
        name="legal.terms.thunderbird",
    ),
    path(
        "terms/mdn-plus/",
        LegalDocView.as_view(template_name="legal/terms/mdn-plus.html", legal_doc_name="mdn_plus_terms"),
        name="legal.terms.mdn-plus",
    ),
    path(
        "terms/services/",
        LegalDocView.as_view(template_name="legal/terms/services.html", legal_doc_name="firefox_cloud_services_ToS"),
        name="legal.terms.services",
    ),
    path(
        "terms/hubs/",
        LegalDocView.as_view(template_name="legal/terms/hubs.html", legal_doc_name="hubs_tos"),
        name="legal.terms.hubs",
    ),
    path(
        "terms/subscription-services/",
        LegalDocView.as_view(template_name="legal/terms/subscription-services.html", legal_doc_name="subscription_services_tos"),
        name="legal.terms.subscription-services",
    ),
    path(
        "acceptable-use/",
        LegalDocView.as_view(template_name="legal/terms/acceptable-use.html", legal_doc_name="acceptable_use_policy"),
        name="legal.terms.acceptable-use",
    ),
    path(
        "report-infringement/",
        LegalDocView.as_view(template_name="legal/report-infringement.html", legal_doc_name="report_infringement"),
        name="legal.report-infringement",
    ),
    path("defend-mozilla-trademarks/", views.fraud_report, name="legal.fraud-report"),
)

bedrock/newsletter/urls.py
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
from django.urls import path, re_path

from bedrock.mozorg.util import page
from bedrock.newsletter import views

# A UUID looks like: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
# Here's a regex to match a UUID:
uuid_regex = r"[0-Fa-f]{8}-[0-Fa-f]{4}-[0-Fa-f]{4}-[0-Fa-f]{4}-[0-Fa-f]{12}"


urlpatterns = (
    # view.existing allows a user who has a link including their token to
    # subscribe, unsubscribe, change their preferences. Each newsletter
    # includes that link for them.
    re_path("^newsletter/existing/(?P<token>[^/]*)/?$", views.existing, name="newsletter.existing.token"),
    # After submitting on the `existing` page, users end up on the
    # `updated` page.  There are optional query params; see the view.
    path("newsletter/updated/", views.updated, name="newsletter.updated"),
    # Confirm subscriptions
    re_path("^newsletter/confirm/(?P<token>%s)/$" % uuid_regex, views.confirm, name="newsletter.confirm"),
    path("newsletter/confirm/thanks/", views.confirm_thanks, name="newsletter.confirm.thanks"),
    # Update country
    re_path("^newsletter/country/(?P<token>[^/]*)/?$", views.set_country, name="newsletter.country"),
    # Request recovery message with link to manage subscriptions
    path("newsletter/recovery/", views.recovery, name="newsletter.recovery"),
    # Receives POSTs from all subscribe forms
    path("newsletter/", views.newsletter_subscribe, name="newsletter.subscribe"),
    # Welcome program opt-out confirmation page (bug 1442129)
    path("newsletter/opt-out-confirmation/", views.recovery, name="newsletter.opt-out-confirmation"),
    # Branded signup pages for individual newsletters
    page("newsletter/mozilla/", "newsletter/mozilla.html", ftl_files=["mozorg/newsletters"]),
    page("newsletter/firefox/", "newsletter/firefox.html", ftl_files=["mozorg/newsletters"]),
    page("newsletter/developer/", "newsletter/developer.html", ftl_files=["mozorg/newsletters"]),
    page("newsletter/fxa-error/", "newsletter/fxa-error.html", ftl_files=["mozorg/newsletters"]),
    page("newsletter/knowledge-is-power/", "newsletter/knowledge-is-power.html", ftl_files=["mozorg/newsletters"]),
    page("newsletter/family/", "newsletter/family.html", ftl_files=["mozorg/newsletters"], active_locales=["en-US"]),
    path("newsletter/newsletter-strings.json", views.newsletter_strings_json, name="newsletter.strings"),
)

bedrock/newsletter/models.py
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

from django.db import models

from django_extensions.db.fields.json import JSONField


class NewsletterManager(models.Manager):
    def serialize(self):
        data = {}
        for nl in self.all():
            data[nl.slug] = nl.data
        return data

    def refresh(self, new_data):
        """Update all data in the table from a dict of Newsletter data

        Return None if nothing changed, or number of records otherwise.
        """
        curr_data = self.serialize()
        if new_data == curr_data:
            return None

        self.all().delete()
        count = 0
        for slug, data in new_data.items():
            self.create(
                slug=slug,
                data=data,
            )
            count += 1

        return count


class Newsletter(models.Model):
    slug = models.SlugField(
        unique=True,
        help_text="The ID for the newsletter that will be used by clients",
    )
    data = JSONField()

    objects = NewsletterManager()

    def __str__(self):
        return self.slug

bedrock/newsletter/forms.py
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
from operator import itemgetter

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import validate_unicode_slug
from django.forms import widgets

from product_details import product_details

from bedrock.mozorg.forms import FORMATS, EmailInput, PrivacyWidget, strip_parenthetical
from bedrock.newsletter import utils
from lib.l10n_utils.fluent import ftl, ftl_lazy


def validate_newsletters(newsletters):
    if not newsletters:
        raise ValidationError("No Newsletter Provided")

    newsletters = [n.replace(" ", "") for n in newsletters]
    for newsletter in newsletters:
        try:
            validate_unicode_slug(newsletter)
        except ValidationError:
            raise ValidationError("Invalid newsletter")

    return newsletters


def get_lang_choices(newsletters=None):
    """
    Return a localized list of choices for language.

    List looks like: [[lang_code, lang_name], [lang_code, lang_name], ...]

    :param newsletters: Either a comma separated string or a list of newsletter ids.
    """
    lang_choices = []
    languages = utils.get_languages_for_newsletters(newsletters)

    for lang in languages:
        if lang in product_details.languages:
            lang_name = product_details.languages[lang]["native"]
        else:
            try:
                locale = [loc for loc in product_details.languages if loc.startswith(lang)][0]
            except IndexError:
                continue
            lang_name = product_details.languages[locale]["native"]
        lang_choices.append([lang, strip_parenthetical(lang_name)])
    return sorted(lang_choices, key=itemgetter(1))


class SimpleRadioSelect(widgets.RadioSelect):
    """
    Render radio buttons as just labels with no <ul> chrome.
    """

    template_name = "newsletter/forms/simple_radio_select.html"


class BooleanTabularRadioSelect(widgets.RadioSelect):
    """
    A Select Widget intended to be used with NullBooleanField.
    """

    template_name = "newsletter/forms/tabular_radio_select.html"
    wrap_label = False

    def __init__(self, attrs=None):
        choices = (
            ("true", ftl("newsletter-form-yes")),
            ("false", ftl("newsletter-form-no")),
        )
        super().__init__(attrs, choices)

    def format_value(self, value):
        try:
            return {
                True: "true",
                False: "false",
                "true": "true",
                "false": "false",
            }[value]
        except KeyError:
            return "unknown"

    def value_from_datadict(self, data, files, name):
        value = data.get(name)
        return {
            True: True,
            False: False,
            "true": True,
            "false": False,
        }.get(value)

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context["wrap_label"] = False
        return context


class CountrySelectForm(forms.Form):
    """
    Form used on a page dedicated to allowing an existing subscriber to provide
    us with their country so that we can include them in mailings relevant to
    their area of the world.
    """

    country = forms.ChoiceField(choices=[])  # will set choices based on locale

    def __init__(self, locale, *args, **kwargs):
        regions = product_details.get_regions(locale)
        regions = sorted(iter(regions.items()), key=itemgetter(1))
        super().__init__(*args, **kwargs)
        self.fields["country"].choices = regions


class ManageSubscriptionsForm(forms.Form):
    """
    Form used on manage subscriptions page for the user's information,
    like email address and language preference.

    @param locale: locale string, e.g. "en-US".  Will be used to set
    country and lang defaults if not otherwise provided in initial
    or bound data.
    @param args: Other standard form args
    @param kwargs: Other standard form kwargs
    """

    format = forms.ChoiceField(widget=SimpleRadioSelect, choices=FORMATS, initial="H")
    remove_all = forms.BooleanField(required=False)

    country = forms.ChoiceField(choices=[], required=False)  # will set choices based on locale
    lang = forms.ChoiceField(choices=[], required=False)  # will set choices based on newsletter languages

    def __init__(self, locale, *args, **kwargs):
        regions_dict = product_details.get_regions(locale)
        regions = [("", ftl_lazy("newsletter-form-select-country-or-region", fallback="newsletter-form-select-country"))] + sorted(
            iter(regions_dict.items()), key=itemgetter(1)
        )
        lang_choices = [("", ftl_lazy("newsletter-form-available-languages"))] + get_lang_choices()
        super().__init__(*args, **kwargs)
        self.fields["country"].choices = regions
        self.fields["lang"].choices = lang_choices


class NewsletterForm(forms.Form):
    """
    Form to let a user subscribe to or unsubscribe from a newsletter
    on the manage existing newsletters page.  Used in a FormSet.
    """

    title = forms.CharField(required=False)
    description = forms.CharField(required=False)
    subscribed_radio = forms.BooleanField(
        widget=BooleanTabularRadioSelect,
        required=False,  # they have to answer, but answer can be False
    )
    subscribed_check = forms.BooleanField(
        widget=widgets.CheckboxInput,
        required=False,  # they have to answer, but answer can be False
    )
    newsletter = forms.CharField(widget=forms.HiddenInput)


class NewsletterFooterForm(forms.Form):
    """
    Form used to subscribe to a single newsletter, typically in the
    footer of a page (see newsletters/middleware.py) but sometimes
    on a dedicated page.
    """

    choice_labels = {
        "mozilla-foundation": ftl("multi-newsletter-form-checkboxes-label-mozilla"),
        "mozilla-and-you": ftl("multi-newsletter-form-checkboxes-label-firefox"),
    }

    email = forms.EmailField(widget=EmailInput(attrs={"required": "required"}))
    # first/last_name not yet included in email_newsletter_form helper
    # currently used on /contribute/friends/ (custom markup)
    first_name = forms.CharField(widget=forms.TextInput, required=False)
    last_name = forms.CharField(widget=forms.TextInput, required=False)
    fmt = forms.ChoiceField(widget=SimpleRadioSelect, choices=FORMATS, initial="H")
    privacy = forms.BooleanField(widget=PrivacyWidget)
    source_url = forms.CharField(required=False)
    newsletters = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple())

    # has to take a newsletters argument so it can figure
    # out which languages to list in the form.
    def __init__(self, newsletters, locale, data=None, *args, **kwargs):
        regions = product_details.get_regions(locale)
        regions = sorted(iter(regions.items()), key=itemgetter(1))

        try:
            if isinstance(newsletters, str):
                newsletters = newsletters.split(",")
            newsletters = validate_newsletters(newsletters)
        except ValidationError:
            # replace with most common good newsletter
            # form validation will work with submitted data
            newsletters = ["mozilla-and-you"]

        lang = locale.lower()
        if "-" in lang:
            lang, country = lang.split("-", 1)
        else:
            country = ""
            regions.insert(0, ("", ftl_lazy("newsletter-form-select-country-or-region", fallback="newsletter-form-select-country")))
        lang_choices = get_lang_choices(newsletters)
        languages = [x[0] for x in lang_choices]
        if lang not in languages:
            # The lang from their locale is not one that our newsletters
            # are translated into. Initialize the language field to no
            # choice, to force the user to pick one of the languages that
            # we do support.
            lang = ""
            lang_choices.insert(0, ("", ftl_lazy("newsletter-form-available-languages")))

        super().__init__(data, *args, **kwargs)

        required_args = {
            "required": "required",
            "aria-required": "true",
        }
        country_widget = widgets.Select(attrs=required_args)
        country_label = ftl_lazy("newsletter-form-select-country-or-region", fallback="newsletter-form-select-country")
        self.fields["country"] = forms.ChoiceField(widget=country_widget, choices=regions, initial=country, required=False, label=country_label)
        lang_widget = widgets.Select(attrs=required_args)
        lang_label = ftl_lazy("newsletter-form-select-language", fallback="newsletter-form-available-languages")
        self.fields["lang"] = forms.TypedChoiceField(widget=lang_widget, choices=lang_choices, initial=lang, required=False, label=lang_label)
        self.fields["newsletters"].choices = [(n, self.choice_labels.get(n, n)) for n in newsletters]
        self.fields["newsletters"].initial = newsletters

    def clean_newsletters(self):
        return validate_newsletters(self.cleaned_data["newsletters"])

    def clean_source_url(self):
        su = self.cleaned_data["source_url"].strip()
        if su:
            # limit to 255 characters by truncation
            return su[:255]

        return su


class EmailForm(forms.Form):
    """
    Form to enter email, e.g. to be sent a recovery message
    """

    email = forms.EmailField(widget=EmailInput(attrs={"required": "required"}))

bedrock/newsletter/templates/newsletter/includes/form.html
{#
 This Source Code Form is subject to the terms of the Mozilla Public
 License, v. 2.0. If a copy of the MPL was not distributed with this
 file, You can obtain one at https://mozilla.org/MPL/2.0/.
#}

{% from "newsletter/includes/macros.html" import email_form_thankyou with context %}

{% if not success %}
  <form id="newsletter-form" class="mzp-c-newsletter-form" action="{{ action }}" method="post">
    {% if not is_multi_newsletter_form %}
      <div hidden>
        {{ form.newsletters|safe }}
      </div>
    {% endif %}
    <input type="hidden" name="source_url" value="{{ request.build_absolute_uri() }}">

    {% if include_title and is_multi_newsletter_form %}
    <header class="mzp-c-newsletter-header">
      <h3 class="mzp-c-newsletter-title">{{ title|d(ftl('multi-newsletter-form-title'), true) }}</h3>
      <p class="mzp-c-newsletter-desc">{{ desc|d(ftl('multi-newsletter-form-desc'), true) }}</p>
    </header>
    {% elif include_title %}
    <header class="mzp-c-newsletter-header">
      <h3 class="mzp-c-newsletter-title">{{ title|d(ftl('newsletter-form-get-firefox-news'), true) }}</h3>
      {% if subtitle %}
      <h4 class="mzp-c-newsletter-subtitle">{{ subtitle }}</h4>
      {% endif %}
      {% if desc %}
      <p class="mzp-c-newsletter-desc">{{ desc }}</p>
      {% endif %}
    </header>
    {% endif %}

    <fieldset class="mzp-c-newsletter-content">
      <div class="mzp-c-form-errors {% if not form.errors %}hidden{% endif %}" id="newsletter-errors">
        {{ form.non_field_errors()|safe }}
        <ul class="mzp-u-list-styled">
          <li class="error-email-invalid {% if not form.email.errors %}hidden{% endif %}">
            {{ ftl('newsletter-form-please-enter-a-valid') }}
          </li>
          <li class="error-select-country {% if not form.country.errors %}hidden{% endif %}">
            {{ ftl('newsletter-form-please-select-country') }}
          </li>
          <li class="error-select-language {% if not form.lang.errors %}hidden{% endif %}">
            {{ ftl('newsletter-form-please-select-language') }}
          </li>
          <li class="error-newsletter-checkbox {% if not form.newsletters.errors %}hidden{% endif %}">
            {{ ftl('multi-newsletter-form-checkboxes-error') }}
          </li>
          <li class="error-privacy-policy {% if not form.privacy.errors %}hidden{% endif %}">
            {{ ftl('newsletter-form-you-must-agree-to') }}
          </li>
          <li class="error-try-again-later hidden">
            {{ ftl('newsletter-form-we-are-sorry-but-there') }}
          </li>
        </ul>
      </div>

      {{ form.email.label_tag(ftl('newsletter-form-your-email-address') if not email_label else email_label) }}
      {% if email_placeholder %}
        {% set placeholder = email_placeholder %}
      {% else %}
        {% set placeholder = ftl('newsletter-form-yournameexamplecom', fallback='newsletter-form-your-email-here') %}
      {% endif %}
      {{ field_with_attrs(form.email, placeholder=placeholder, class='mzp-js-email-field')|safe }}

      <div id="newsletter-details" class="mzp-c-newsletter-details">
        {% if include_country %}
          {{ form.country.label_tag() }}
          <p>{{ form.country|safe }}</p>
        {% endif %}

        {% if include_language %}
          {{ form.lang.label_tag() }}
          <p>{{ form.lang|safe }}</p>
        {% else %}
          <input type="hidden" name="lang" id="id_lang"  value="en">
        {% endif %}

        {% if is_multi_newsletter_form %}
          <fieldset class="mzp-u-inline">
            <legend>{{ ftl('multi-newsletter-form-checkboxes-legend') }}</legend>
            <p>
              {% for field in form.newsletters %}
                <label for="{{ field.id_for_label }}" class="mzp-u-inline">
                  {{ field.tag() }} {{ field.choice_label }}
                </label>
              {% endfor %}
            </p>
          </fieldset>
        {% endif %}

        <fieldset class="mzp-u-inline">
          <legend>{{ ftl('newsletter-form-format') }}</legend>
          <p>
            <label for="format-html" class="mzp-u-inline">
              <input type="radio" id="format-html" name="format" value="H" checked> {{ ftl('newsletter-form-html') }}
            </label>
            <label for="format-text" class="mzp-u-inline">
              <input type="radio" id="format-text" name="format" value="T"> {{ ftl('newsletter-form-text') }}
            </label>
          </p>
        </fieldset>

        <p>
          <label for="privacy" class="mzp-u-inline">
            <input type="checkbox" id="privacy" name="privacy" required aria-required="true"> {{ ftl('newsletter-form-im-okay-with-mozilla', url=url('privacy.notices.websites')) }}
          </label>
        </p>
      </div>

      <p class="mzp-c-form-submit">
        <button type="submit" id="newsletter-submit" class="mzp-c-button {{ button_class }}" data-cta-type="Newsletter-{{ id }}" data-cta-text="Newsletter Sign Up">
          {% if submit_text %}
            {{ submit_text }}
          {% else %}
            {{ ftl('newsletter-form-sign-up-now', fallback='newsletter-form-sign-me-up') }}
          {% endif %}
        </button>

        {% if details %}
          <span class="mzp-c-fieldnote">{{ details }}</span>
        {% elif not is_multi_newsletter_form %}
            <span class="mzp-c-fieldnote">
              {# Issue 7460 `mozilla-and-you` is the ID for the Firefox newsletter, because history... #}
              {% if id == 'mozilla-and-you' %}
                {{ ftl('newsletter-form-we-will-only-send-firefox', fallback='newsletter-form-we-will-only-send') }}
              {% else %}
                {{ ftl('newsletter-form-we-will-only-send') }}
              {% endif %}
            </span>
        {% endif %}
      </p>
    </fieldset>
  </form>

  <div id="newsletter-thanks" class="mzp-c-newsletter-thanks hidden">
    {% if thankyou_content %}
      <h3>{{ thankyou_head }}</h3>
      <p>{{ thankyou_content }}</p>
    {% else %}
      {{ email_form_thankyou() }}
    {% endif %}
  </div>

{% elif use_thankyou %}
  <div id="newsletter-thanks">
    {% if thankyou_content %}
      <h3>{{ thankyou_head }}</h3>
      <p>{{ thankyou_content }}</p>
    {% else %}
      {{ email_form_thankyou() }}
    {% endif %}
  </div>
{% endif %}

bedrock/newsletter/templates/newsletter/includes/macros.html
{#
 This Source Code Form is subject to the terms of the Mozilla Public
 License, v. 2.0. If a copy of the MPL was not distributed with this
 file, You can obtain one at https://mozilla.org/MPL/2.0/.
#}

{% macro email_form_thankyou() %}
  <h3>{{ ftl('newsletter-form-thanks') }}</h3>
  <p>{{ ftl('newsletter-form-if-you-havent-previously') }}</p>
{% endmacro %}